#公共配置，所有服务共享
server:
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true

#redis配置
redis:
  host: 127.0.0.1
  password:
  port: 6379
  pool:
    max-idle: 100
    min-idle: 1
    max-active: 1000
    max-wait: -1